version: "3"

services:
  app:
    build:
      context: ./app/
    platform: linux/amd64
    volumes:
      - type: bind
        source: ./app/src/
        target: /home/local/
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
